# Name: Sharon Yi
# Project: Launch-Tube

# This is a Makefile for my lab assignment. It allows me to easily and accurately rebuild
# the lab assignment.


# EXECUTABLES is a Make Variable (similar to an environment variable) that lists all the
# "executables" associated with the lab. 
EXECUTABLES1=launch tube
EXECUTABLES2=launch
EXECUTABLES3=tube
SRC=launch.c tube.c
OBJ=launch.o tube.o
SRC1=launch.c
OBJ1=launch.o
SRC2=tube.c
OBJ12=tube.o


#EXECUTABLES=Tube
#SRC=Tube.c
#OBJ=Tube.o

# The CC and CFLAGS variables are defined to ensure I'm using the native compiler and
# that the correct command-line options are set
CC=gcc
CFLAGS=-g

# Here is my default target for the Makefile.  When I type make, this first target will
# be created. I.e., all the executables
all: launch tube

launch: launch.c
	$(CC) $(CFLAGS) -c launch.c
	$(CC) $(CFLAGS) -o $@ launch.o
tube: tube.c
	$(CC) $(CFLAGS) -c tube.c
	$(CC) $(CFLAGS) -o $@ tube.o

# On the following lines (which _must_ start with a tab), are the commands I need to type -- 
# each time my source file is modified.
$(EXECUTABLES): $(SRC)
	$(CC) $(CFLAGS) -c $(SRC)
	$(CC) $(CFLAGS) -o $@ $(OBJ)

# By convention, I always have a target called
# "clean" that I used to define all temporary
# or intermediates.
clean:
	rm -f $(EXECUTABLES1) $(OBJ) *~
	rm -f $(EXECUTABLES2) $(OBJ1) *~
	rm -f $(EXECUTABLES3) $(OBJ2) *~

