CC = gcc

all:
	$(CC) -c catcher.c -Wall -Wextra
	$(CC) -o catcher catcher.o -lm
catcher: catcher.c
	$(CC) -c catcher.c -Wall -Wextra
	$(CC) -o catcher catcher.o -lm

clean:
	rm -f catcher catcher.o *~
